---
environment:
  matrix:
    - PYTHON: "C:\\Python27"
      LXML: "3.5.0"
    - PYTHON: "C:\\Python27"
      LXML: "4.3.0"
    - PYTHON: "C:\\Python33"
      LXML: "3.5.0"
    - PYTHON: "C:\\Python33"
      LXML: "4.3.0"
    - PYTHON: "C:\\Python34"
      LXML: "3.5.0"
    - PYTHON: "C:\\Python34"
      LXML: "4.3.0"
    - PYTHON: "C:\\Python35"
      LXML: "3.5.0"
    - PYTHON: "C:\\Python35"
      LXML: "4.3.0"
    - PYTHON: "C:\\Python36"
      LXML: "3.5.0"
    - PYTHON: "C:\\Python36"
      LXML: "4.3.0"
    - PYTHON: "C:\\Python37"
      LXML: "3.5.0"
    - PYTHON: "C:\\Python37"
      LXML: "4.3.0"

init:
  - "%PYTHON%/python -V"
  - "%PYTHON%/python -c \"import struct;print( 8 * struct.calcsize(\'P\'))\""

install:
  - "%PYTHON%/Scripts/easy_install -U pip"
  - "%PYTHON%/Scripts/easy_install lxml==%LXML"
  - "%PYTHON%/Scripts/pip install wheel"
  - "%PYTHON%/Scripts/pip install -e .[test]"


build: false  # Not a C# project, build stuff at the test step instead.

test_script:
  - "%PYTHON%/Scripts/py.test --cov=zeep --cov-report=term-missing"

after_test:
  - "%PYTHON%/python setup.py bdist_wheel"
  - ps: "ls dist"

artifacts:
  - path: dist\*
